### ISSUE TITLE
Keys like "yes" and "on" are read as true

### ISSUE THREAD

**Issue by slntopp** [ghodss/yaml#77]
```golang
template = `
on:
 - RUNNING
`
template, _ = yaml.YAMLToJSON(template)
fmt.Println(string(template))
// => {"true":["DELETED"]}
```

**Comment by s1moe2** [comment]
I was about to open a similar issue. `y` is also read as true.
Not great but solved by quoting the property: `"y"`

**Comment by slntopp** [comment]
yeah, I figured too, but unfortunately not a solution in my case :(

**Comment by fproulx-boostsecurity** [comment]
We have the same issue. It affects https://github.com/open-policy-agent/opa which uses this library.

**Comment by samlown** [comment]
I can see that would have been very annoying! It's to do with the way yaml.v2 was parsing keys as `interface{}` instead of `string.`. That still happens in yaml.v3, but only if *all* keys are non-strings. Moving to v3 should fix this.

Doesn't look there was much maintenance here, so I've forked this repo and upgraded to v3 if you'd like to test it: https://github.com/invopop/yaml

**Comment by slyt** [comment]
Ran into this same issue today:

`n: "hello"` gets converted to `{"false":"hello"}`

`"n": "hello"` gets converted to `{"n":"hello"}` so quoting your YAML keys is a workaround

**Comment by slyt** [comment]
This happens for both keys and values if unquotted y, n, Y, N:

```go
package main

import (
	"fmt"
	"io/ioutil"
	"log"

	"github.com/ghodss/yaml"
)

func main() {
	// Read the YAML file.
	yamlFile := "input.yaml"
	yamlData, err := ioutil.ReadFile(yamlFile)
	if err != nil {
		log.Fatalf("Error reading YAML file: %v", err)
	}

	// Convert YAML to JSON.
	jsonData, err := yaml.YAMLToJSON(yamlData)
	if err != nil {
		log.Fatalf("Error converting YAML to JSON: %v", err)
	}

	// Print the resulting JSON.
	fmt.Println(string(jsonData))
}

```

input.yaml
```yaml
n: 
  title: N
  type: integer
  default: 1
y:
  nested:
    n:
      nested:
        title: Y
        title_2: N
```

converts to:
```json
{
  "false": { "default": 1, "title": false, "type": "integer" },
  "true": {
    "nested": { "false": { "nested": { "title": true, "title_2": false } } }
  }
}
```
